name: perturb_seq_env
channels:
  - conda-forge
dependencies:
  - python
  - scanpy
  - muon
  - anndata
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotnine
  - scipy
  - scikit-learn
  - joblib
  - tqdm