name: perturb_seq_env
channels:
  - conda-forge
dependencies:
  - python
  - scanpy
  - muon
  - pip
  - anndata
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - plotnine
  - scipy
  - scikit-misc
  - scikit-learn
  - joblib
  - tqdm
  - ipython
  - dcor
  - sphinx
  - mscorefonts
  - sphinx_rtd_theme  # Optional: A popular theme for Sphinx documentation
  - myst-parser       # Optional: If you want to include Markdown files
  - pip:
    - pydeseq2
    - plotly
    - pymde
    - leidenalg
    - igraph